### ISSUE TITLE
Add sponsors to homepage

### ISSUE THREAD

**Issue by padr31** [hackkosice/new-web#3]
- Sponsors in platinum, gold, and bronze sections are added
- New sponsors can be easily added by just adding a tier, logo, and name. 
- Add tutorial on how sponsors can be added/deleted here https://www.notion.so/hackkosice/Tutorials-b1a77b110d304a28a0f775f8dc6840d6

**Comment by padr31** [comment]
Currently, there is no color on which all logos look great. I suggest we use white - for that we need to collect logos from sponsors who currently have white logos.

**Comment by padr31** [comment]
Did not find logos for zagx, mlh, and menahacks in drive. Handing this over to @pridilla

**Comment by padr31** [comment]
Gathered all the logos in the end. This is how it looks like
![Uploading image.png…]()

**Comment by jjurm** [comment]
Thanks! The logos have different-sized (and unpredictable) clickable areas, which may be an issue especially on phones. Constant height doesnt work because logos have variable sizes (due to the `col-lg-2 col-md-3 col-sm-4` class). I tried to make at least `.award-img-block` elements always squares in dc68a93bf30b9b5337c4635d896b4629cb55c9d2.

**Comment by padr31** [comment]
What you can do is convert all the logos to the same underlying square image format (like the source image format, not the html).  I don't think this is an issue and won't be doing it manually, happy to close.

**Comment by jjurm** [comment]
Ok, finally solved square links for sponsor logos by CSS (0004d573)
